# This file was generated by GoReleaser. DO NOT EDIT.
cask "enventory" do
  version "0.0.27"

  on_macos do
    on_intel do
      sha256 "c88b15b3c23759469a1b4c6ac4409f045adf3d7f764660e0ef04f9a7fae9d62d"
      url "https://github.com/bbkane/enventory/releases/download/v#{version}/enventory_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "031e6659852169297c927d54971d74fa90dc9696c6c0555725aad4d990b4ba9d"
      url "https://github.com/bbkane/enventory/releases/download/v#{version}/enventory_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4eb1e2ebbad71fc2a8f52aa062f5071dae51d15dc52b5963e9d33a91f39e2df1"
      url "https://github.com/bbkane/enventory/releases/download/v#{version}/enventory_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e48f4194051b9f2a9c0d4258ce88e2524f2dd4dfd2a60c2001560a7ab71bdfb4"
      url "https://github.com/bbkane/enventory/releases/download/v#{version}/enventory_#{version}_linux_arm64.tar.gz"
    end
  end

  name "enventory"
  desc "Centrally manage environment variables"
  homepage "https://github.com/bbkane/enventory"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "enventory"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/enventory"] if OS.mac?
  end
  generate_completions_from_executable "enventory", "completion",
    shells: [:bash, :fish, :zsh]

  # No zap stanza required

  caveats <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
end
