# This file was generated by GoReleaser. DO NOT EDIT.
cask "enventory" do
  version "0.0.28"

  on_macos do
    on_intel do
      sha256 "2a22628565ee6bda8779df5bda5efac30d1d31c4b0cabede7d986b793ee328fe"
      url "https://github.com/bbkane/enventory/releases/download/v#{version}/enventory_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "79a6dff808e2433a3ffa5bf994e23600b4ca3395a1be58e0dc9affcbe5ad01fa"
      url "https://github.com/bbkane/enventory/releases/download/v#{version}/enventory_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "527aacb6b9955e235f607c9214e5c64c2ccc5940aae4cf214364c796bf9927f9"
      url "https://github.com/bbkane/enventory/releases/download/v#{version}/enventory_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6ee7eb4219c816d14042020d4f22774f8cf4a845f975bc3fd588e54f687f7f6"
      url "https://github.com/bbkane/enventory/releases/download/v#{version}/enventory_#{version}_linux_arm64.tar.gz"
    end
  end

  name "enventory"
  desc "Centrally manage environment variables"
  homepage "https://github.com/bbkane/enventory"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "enventory"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/enventory"] if OS.mac?
  end
  generate_completions_from_executable "enventory", "completion",
    shells: [:zsh]

  # No zap stanza required

  caveats <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
end
