# This file was generated by GoReleaser. DO NOT EDIT.
cask "example-go-cli" do
  version "0.0.22"

  on_macos do
    on_intel do
      sha256 "fa2c0d0e14cd9e237533c43895985000ad45e0e4d13f0b216bcee09c1a8ff077"
      url "https://github.com/bbkane/example-go-cli/releases/download/v#{version}/example-go-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0107a8f12df1ca841d15018423359a0895d57f9af47d3db89eb9093c21cdd8ad"
      url "https://github.com/bbkane/example-go-cli/releases/download/v#{version}/example-go-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bca04b6a5c7ca1ae6b814a667445397bde016ba8772ac3b9ce432ecead0e009e"
      url "https://github.com/bbkane/example-go-cli/releases/download/v#{version}/example-go-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "53dfacaf26a63ad8551e41c6599a9880e5b5ff92995b7fac68cebb47dac4da33"
      url "https://github.com/bbkane/example-go-cli/releases/download/v#{version}/example-go-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "example-go-cli"
  desc "Example Go CLI to model tooling"
  homepage "https://github.com/bbkane/example-go-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "example-go-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/example-go-cli"] if OS.mac?
  end
  generate_completions_from_executable "example-go-cli", "completion",
    shells: [:bash, :fish, :zsh]

  # No zap stanza required

  caveats <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
end
