# This file was generated by GoReleaser. DO NOT EDIT.
cask "example-rust-cli" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "f7d04d92f9928c7f2547bcd1f62126d5e420e15fe86efbd53d035d9c59da5177"
      url "https://github.com/bbkane/example-rust-cli/releases/download/v#{version}/example-rust-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2bfd96d4a67772e861de20bff576557b30e9daf0d66dcab518cb63e51845d483"
      url "https://github.com/bbkane/example-rust-cli/releases/download/v#{version}/example-rust-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6b8fc1fb2f411be8ac66da676cb6a9cfbdeddd4dfe13d68937b762d8587c4a32"
      url "https://github.com/bbkane/example-rust-cli/releases/download/v#{version}/example-rust-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cb69fb58fac1eda7dd31443c2b4332411d7460096879f249c89d71b01093c051"
      url "https://github.com/bbkane/example-rust-cli/releases/download/v#{version}/example-rust-cli_Linux_arm64.tar.gz"
    end
  end

  name "example-rust-cli"
  desc "Example Rust CLI to model tooling"
  homepage "https://github.com/bbkane/example-rust-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "example-rust-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/example-rust-cli"] if OS.mac?
  end

  # No zap stanza required

  caveats <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
end
