# This file was generated by GoReleaser. DO NOT EDIT.
cask "example-go-cli" do
  version "0.0.21"

  on_macos do
    on_intel do
      sha256 "96930a6e0a2167400a113b08aab4ca33b6659ab1534e1651d083bfcd45f4ad73"
      url "https://github.com/bbkane/example-go-cli/releases/download/v#{version}/example-go-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d199e572479e31ff3c3cbaada408ebfe669809d038cfe4c2b2a76ea20a74dfe"
      url "https://github.com/bbkane/example-go-cli/releases/download/v#{version}/example-go-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7556b04adcf071b9f44bf0509b250ca3f8123c5c091cda58739b609285f374a6"
      url "https://github.com/bbkane/example-go-cli/releases/download/v#{version}/example-go-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "45e58d9e2238cdc7fe2c245deb22b0dc020aa5495e0c5e07ccb6f5b4922d8cec"
      url "https://github.com/bbkane/example-go-cli/releases/download/v#{version}/example-go-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "example-go-cli"
  desc "Example Go CLI to model tooling"
  homepage "https://github.com/bbkane/example-go-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "example-go-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/example-go-cli"] if OS.mac?
  end
  generate_completions_from_executable "example-go-cli", "completion",
    shells: [:bash, :fish, :zsh]

  # No zap stanza required

  caveats <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
end
