# This file was generated by GoReleaser. DO NOT EDIT.
cask "example-go-cli" do
  version "0.0.23"

  on_macos do
    on_intel do
      sha256 "1e4f82125669fff4504c21fe53852aff8e6680d67aa9078ff5db652eee71b4fb"
      url "https://github.com/bbkane/example-go-cli/releases/download/v#{version}/example-go-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "59b5f0cb0bcb49e621645e72625a383b49925e630e3b1b9f245a2aae4039c0b4"
      url "https://github.com/bbkane/example-go-cli/releases/download/v#{version}/example-go-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "154a2e24023e25844c3458933fc3b0d43f698b06c40422f2a11f5c5fefe46a75"
      url "https://github.com/bbkane/example-go-cli/releases/download/v#{version}/example-go-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2a1b7862f66a05707d5d978e291abcb88b80dc31df0a370d21c22582c6aff18d"
      url "https://github.com/bbkane/example-go-cli/releases/download/v#{version}/example-go-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "example-go-cli"
  desc "Example Go CLI to model tooling"
  homepage "https://github.com/bbkane/example-go-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "example-go-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/example-go-cli"] if OS.mac?
  end
  generate_completions_from_executable "example-go-cli", "completion",
    shells: [:bash, :fish, :zsh]

  # No zap stanza required

  caveats <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
end
