# This file was generated by GoReleaser. DO NOT EDIT.
cask "example-rust-cli" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "2cdd9d45bfbe66f82828a8ff17d38ce9a8e9daa1edea8b61bb56e3c7cb0b795c"
      url "https://github.com/bbkane/example-rust-cli/releases/download/v#{version}/example-rust-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7047d9f3604710d3d09e092837b78e194813646dd88614012dffab9c3fe7eece"
      url "https://github.com/bbkane/example-rust-cli/releases/download/v#{version}/example-rust-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "de39cb6d9baf5a467e90b22a38c35c42447a6a9ac1f1571bd1e43f59351ddd34"
      url "https://github.com/bbkane/example-rust-cli/releases/download/v#{version}/example-rust-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "19e1673dfea00d3464f8637af5dc723c9faf7a5fc1bcefdb4d2e6a472093aa7e"
      url "https://github.com/bbkane/example-rust-cli/releases/download/v#{version}/example-rust-cli_Linux_arm64.tar.gz"
    end
  end

  name "example-rust-cli"
  desc "Example Rust CLI to model tooling"
  homepage "https://github.com/bbkane/example-rust-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "example-rust-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/example-rust-cli"] if OS.mac?
  end
  generate_completions_from_executable "example-rust-cli", "completion"

  # No zap stanza required

  caveats <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
end
