# This file was generated by GoReleaser. DO NOT EDIT.
cask "example-rust-cli" do
  version "0.1.8"

  on_macos do
    on_intel do
      sha256 "1f966b9c76ff68b0f6fdbb228724d43a48fb4feeca4e9f8bcd96b15cd36bda2e"
      url "https://github.com/bbkane/example-rust-cli/releases/download/v#{version}/example-rust-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "545e631d7b0fa418d093d8f3a3140aabfcbe6c91b21f4fd96ba631cff0c3170e"
      url "https://github.com/bbkane/example-rust-cli/releases/download/v#{version}/example-rust-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "70f0e8a621bf4c1877a620f2b1e57c0ce1519c9d8b40692b1a042d72dca7816d"
      url "https://github.com/bbkane/example-rust-cli/releases/download/v#{version}/example-rust-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ddb316eb30628582c3911bdccaf0b0fffff6fdc9661e25c06568a00a0e6c1a28"
      url "https://github.com/bbkane/example-rust-cli/releases/download/v#{version}/example-rust-cli_Linux_arm64.tar.gz"
    end
  end

  name "example-rust-cli"
  desc "Example Rust CLI to model tooling"
  homepage "https://github.com/bbkane/example-rust-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "example-rust-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/example-rust-cli"] if OS.mac?
  end
  generate_completions_from_executable "example-rust-cli", "completion"

  # No zap stanza required

  caveats <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
end
