# This file was generated by GoReleaser. DO NOT EDIT.
cask "fling" do
  version "0.0.25"

  on_macos do
    on_intel do
      sha256 "035f1dcf6c4b4c0243f18a39f237186be6dee2eb6d6086dd03cc8ebc17565b8f"
      url "https://github.com/bbkane/fling/releases/download/v#{version}/fling_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "38aa30dd4abe39311d529aff3d62ea6b1b9aa63aecf202a3f4b966cd03854312"
      url "https://github.com/bbkane/fling/releases/download/v#{version}/fling_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7bfb1e6053a78a5c906965f9a75788cda8865314c0682edbdf116b369e15a27a"
      url "https://github.com/bbkane/fling/releases/download/v#{version}/fling_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf5a6052e7f7512735b80236dd89bb4fa6133d7ed6be11990ae5abb1aacc6bff"
      url "https://github.com/bbkane/fling/releases/download/v#{version}/fling_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fling"
  desc "GNU Stow alternative for dotfiles"
  homepage "https://github.com/bbkane/fling"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fling"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fling"] if OS.mac?
  end
  generate_completions_from_executable "fling", "completion",
    shells: [:bash, :fish, :zsh]

  # No zap stanza required

  caveats <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
end
