# This file was generated by GoReleaser. DO NOT EDIT.
cask "grabbit" do
  version "5.0.2"

  on_macos do
    on_intel do
      sha256 "720d2f203fa46918c30e972dd18fd7ff7d1f20c2629497303ce5029ee914f132"
      url "https://github.com/bbkane/grabbit/releases/download/v#{version}/grabbit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f52ad69a9e7ec3903f1a02aec8eed94ea8ae97df5f865633ba9b15f2a62bbda5"
      url "https://github.com/bbkane/grabbit/releases/download/v#{version}/grabbit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec61550c3ff6a950f0e1d11a01dbf50d4318226b019e1dd02c7199f66034de01"
      url "https://github.com/bbkane/grabbit/releases/download/v#{version}/grabbit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cc62bb9751ca22be3484e1eb1d52cb755e85e188e10ce181ee6f4eeeb8725f65"
      url "https://github.com/bbkane/grabbit/releases/download/v#{version}/grabbit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "grabbit"
  desc "Grab images from subreddits! Useful for getting interesting wallpapers"
  homepage "https://github.com/bbkane/grabbit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grabbit"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grabbit"] if OS.mac?
  end
  generate_completions_from_executable "grabbit", "completion",
    shells: [:bash, :fish, :zsh]

  # No zap stanza required

  caveats <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
end
