# This file was generated by GoReleaser. DO NOT EDIT.
cask "toddlerevents" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "a5c10dcac5cbcd9ef669d67009089cd43764afdc8a376e05af8a55b4c0844f32"
      url "https://github.com/bbkane/toddlerevents/releases/download/v#{version}/toddlerevents_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2148b9c510d04e08451b9997e40e975ec31dd3bb7ee4694267914d730fbd11f1"
      url "https://github.com/bbkane/toddlerevents/releases/download/v#{version}/toddlerevents_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c09c1928c96413bef36acfa89e33700cbd9054d662048b9cfb7cc547a84d47af"
      url "https://github.com/bbkane/toddlerevents/releases/download/v#{version}/toddlerevents_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e569f7317802c31a05e21147d21423fcca8c8b920e148ba6f69b0c136cbe9fef"
      url "https://github.com/bbkane/toddlerevents/releases/download/v#{version}/toddlerevents_#{version}_linux_arm64.tar.gz"
    end
  end

  name "toddlerevents"
  desc "Write Bay Area toddler library events to a README.md"
  homepage "https://github.com/bbkane/toddlerevents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toddlerevents"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toddlerevents"] if OS.mac?
  end
  generate_completions_from_executable "toddlerevents", "completion",
    shells: [:bash, :fish, :zsh]

  # No zap stanza required

  caveats <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
end
