# This file was generated by GoReleaser. DO NOT EDIT.
cask "toddlerevents" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "28c2519f77a6db51116031f0c87585ea2f34bdf77e7783b9b25654ed7e63a127"
      url "https://github.com/bbkane/toddlerevents/releases/download/v#{version}/toddlerevents_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the toddlerevents
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      sha256 "5af8c526ee8d9c14c8289018555416faed448fe74b9339f68c6c59ce2d7a2bc6"
      url "https://github.com/bbkane/toddlerevents/releases/download/v#{version}/toddlerevents_#{version}_linux_amd64.tar.gz"
    end
  end

  name "toddlerevents"
  desc "Write Bay Area toddler library events to a README.md"
  homepage "https://github.com/bbkane/toddlerevents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toddlerevents"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toddlerevents"] if OS.mac?
  end
  generate_completions_from_executable "toddlerevents", "completion",
    shells: [:bash, :fish, :zsh]

  # No zap stanza required

  caveats <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
end
