# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enventory < Formula
  desc "Centrally manage environment variables"
  homepage "https://github.com/bbkane/enventory"
  version "0.0.24"

  on_macos do
    url "https://github.com/bbkane/enventory/releases/download/v0.0.24/enventory_0.0.24_darwin_amd64.tar.gz"
    sha256 "5ad331f641bc978d3139c67428521fddca14b8760064a28fe932c0308288844a"

    def install
      bin.install "enventory"
      generate_completions_from_executable(bin/"enventory", "completion", shells: [:zsh])
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Enventory
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bbkane/enventory/releases/download/v0.0.24/enventory_0.0.24_linux_amd64.tar.gz"
      sha256 "735aa6034c23976c4026f8c88e7dcc24d087c71fdb88c5c26143791d04eeef9e"
      def install
        bin.install "enventory"
        generate_completions_from_executable(bin/"enventory", "completion", shells: [:zsh])
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
