# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enventory < Formula
  desc "Centrally manage environment variables"
  homepage "https://github.com/bbkane/enventory"
  version "0.0.20"

  on_macos do
    url "https://github.com/bbkane/enventory/releases/download/v0.0.20/enventory_0.0.20_darwin_amd64.tar.gz"
    sha256 "5893e2b87ca2acd7593d7b227c451439353ede0f07a1f77c965e95c45e691fc9"

    def install
      bin.install "enventory"
      generate_completions_from_executable(bin/"enventory", "completion", shells: [:zsh])
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Enventory
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/bbkane/enventory/releases/download/v0.0.20/enventory_0.0.20_linux_amd64.tar.gz"
      sha256 "ebebc631d793f4b197b8362e89580347e46af3162e3aefbe841f01d7fd534c16"
      def install
        bin.install "enventory"
        generate_completions_from_executable(bin/"enventory", "completion", shells: [:zsh])
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
