# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envelope < Formula
  desc "Example Go CLI to model tooling"
  homepage "https://github.com/bbkane/envelope"
  version "0.0.5"

  on_macos do
    url "https://github.com/bbkane/envelope/releases/download/v0.0.5/envelope_0.0.5_darwin_amd64.tar.gz"
    sha256 "9fd3f48fec6bb821d5668f12e1f0e83ff0e45291c270dc6629082b625c50c91f"

    def install
      bin.install "envelope"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Envelope
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/envelope/releases/download/v0.0.5/envelope_0.0.5_linux_amd64.tar.gz"
      sha256 "4cb019a6acfb72f51d19d6940109831b7d2e77a7551c9c2cffd7e070df261876"

      def install
        bin.install "envelope"
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
