# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envelope < Formula
  desc "Example Go CLI to model tooling"
  homepage "https://github.com/bbkane/envelope"
  version "0.0.13"

  on_macos do
    url "https://github.com/bbkane/envelope/releases/download/v0.0.13/envelope_0.0.13_darwin_amd64.tar.gz"
    sha256 "b689f2b496dbfcc0eaa9c6b39cd0f769ded4f89b446e3500d8432f657e4dc2ed"

    def install
      bin.install "envelope"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Envelope
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bbkane/envelope/releases/download/v0.0.13/envelope_0.0.13_linux_amd64.tar.gz"
        sha256 "49d021a0fe6a53bcfa4c5d4f9c40587eff73d972ba349bbd55284aa02e470c94"

        def install
          bin.install "envelope"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
