# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enventory < Formula
  desc "Centrally manage environment variables"
  homepage "https://github.com/bbkane/enventory"
  version "0.0.26"

  on_macos do
    url "https://github.com/bbkane/enventory/releases/download/v0.0.26/enventory_0.0.26_darwin_amd64.tar.gz"
    sha256 "9b15cd3c5ec0b63555e53a02123c191c9a623d3e39f3f8422216d21549f4f619"

    define_method(:install) do
      bin.install "enventory"
      generate_completions_from_executable(bin/"enventory", "completion", shells: [:bash, :fish, :zsh])
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Enventory
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bbkane/enventory/releases/download/v0.0.26/enventory_0.0.26_linux_amd64.tar.gz"
      sha256 "48d04b9b3e6983d0d3c4d1b638a6cc43503cfdcc719bc420354472125aa01827"
      define_method(:install) do
        bin.install "enventory"
        generate_completions_from_executable(bin/"enventory", "completion", shells: [:bash, :fish, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
