# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExampleGoCli < Formula
  desc "Example Go CLI to model tooling"
  homepage "https://github.com/bbkane/example-go-cli"
  version "0.0.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/example-go-cli/releases/download/v0.0.13/example-go-cli_0.0.13_darwin_amd64.tar.gz"
      sha256 "252f659d4d6afee0de81a9ef6a7c32b4b97cc96ba18ed55149e80161d6d22616"

      def install
        bin.install "example-go-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bbkane/example-go-cli/releases/download/v0.0.13/example-go-cli_0.0.13_darwin_arm64.tar.gz"
      sha256 "5eaa4631ff31e15f59b49a6c63fc6f46287e29700e8d754930f0530b9dfb0582"

      def install
        bin.install "example-go-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bbkane/example-go-cli/releases/download/v0.0.13/example-go-cli_0.0.13_linux_arm64.tar.gz"
      sha256 "3e167b541c2eaa73fb2214c9d4d19eb719e2a07a906310c89bf11799150b9c17"

      def install
        bin.install "example-go-cli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/bbkane/example-go-cli/releases/download/v0.0.13/example-go-cli_0.0.13_linux_armv6.tar.gz"
      sha256 "3457344ab8c86d03fdda72544e635b076d6cab6727a780067cb51780726dae59"

      def install
        bin.install "example-go-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/example-go-cli/releases/download/v0.0.13/example-go-cli_0.0.13_linux_amd64.tar.gz"
      sha256 "75c75df528074475ac8a3a44c5b1a210d2d2847428f03f11bcce8be6ff900faa"

      def install
        bin.install "example-go-cli"
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
