# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExampleGoCli < Formula
  desc "Example Go CLI to model tooling"
  homepage "https://github.com/bbkane/example-go-cli"
  version "0.0.14"

  on_macos do
    url "https://github.com/bbkane/example-go-cli/releases/download/v0.0.14/example-go-cli_0.0.14_darwin_amd64.tar.gz"
    sha256 "e717fa778ab349826075d73a3b035f84ad17dcf18a9d8dde1b2585ec869684b1"

    def install
      bin.install "example-go-cli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the ExampleGoCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/example-go-cli/releases/download/v0.0.14/example-go-cli_0.0.14_linux_amd64.tar.gz"
      sha256 "dbefd6b328b134475e4808136b7a5687316a069b8e3aa4125f5d8aed9c27b81e"

      def install
        bin.install "example-go-cli"
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
