# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExampleGoCli < Formula
  desc "Example Go CLI to model tooling"
  homepage "https://github.com/bbkane/example-go-cli"
  version "0.0.18"

  on_macos do
    url "https://github.com/bbkane/example-go-cli/releases/download/v0.0.18/example-go-cli_0.0.18_darwin_amd64.tar.gz"
    sha256 "a34b077595c8067e2653ec23693299df7e32cad943f1091717d10183a5ee9e92"

    define_method(:install) do
      bin.install "example-go-cli"
      generate_completions_from_executable(bin/"example-go-cli", "completion", shells: [:zsh])
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the ExampleGoCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bbkane/example-go-cli/releases/download/v0.0.18/example-go-cli_0.0.18_linux_amd64.tar.gz"
      sha256 "e2254ad7db5f0daa40b23754aaaeaa4c9f2c1669166ace705e4efbeaf47d1139"
      define_method(:install) do
        bin.install "example-go-cli"
        generate_completions_from_executable(bin/"example-go-cli", "completion", shells: [:zsh])
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
