# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fling < Formula
  desc "GNU Stow alternative for dotfiles"
  homepage "https://github.com/bbkane/fling"
  version "0.0.21"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/fling/releases/download/v0.0.21/fling_0.0.21_darwin_amd64.tar.gz"
      sha256 "2d73c999c98afed3234be8956f5961d666b23fb3a2059850101bb1582d155337"

      def install
        bin.install "fling"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bbkane/fling/releases/download/v0.0.21/fling_0.0.21_darwin_arm64.tar.gz"
      sha256 "b2bc44749f6d17964ecdbd6f1ffab006a73098136bbe6388a54cf5999bf403d5"

      def install
        bin.install "fling"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bbkane/fling/releases/download/v0.0.21/fling_0.0.21_linux_amd64.tar.gz"
        sha256 "c85695e126e766304453a5a178fcc70174d6b1cb3a3d8f2b3de5f76caa6055d2"

        def install
          bin.install "fling"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/bbkane/fling/releases/download/v0.0.21/fling_0.0.21_linux_armv6.tar.gz"
        sha256 "11a17dd73536b3181f2ad6d1fae1436056d4cac3d77c056377dcd2f4882191e9"

        def install
          bin.install "fling"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bbkane/fling/releases/download/v0.0.21/fling_0.0.21_linux_arm64.tar.gz"
        sha256 "76384dd16115fbb50b0042719337bc6a15098948d5bbef9f1b837806342e4463"

        def install
          bin.install "fling"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
