# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fling < Formula
  desc "GNU Stow alternative for dotfiles"
  homepage "https://github.com/bbkane/fling"
  version "0.0.20"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bbkane/fling/releases/download/v0.0.20/fling_0.0.20_darwin_arm64.tar.gz"
      sha256 "78be27bfc27aefec8ffe62ffdd945cfa25d65ea3ed28dcfe81501b6f84eeab1a"

      def install
        bin.install "fling"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/fling/releases/download/v0.0.20/fling_0.0.20_darwin_amd64.tar.gz"
      sha256 "c5b075054da1634d96d9b3a7980e0369098354149d3c9284fc6853d155c3d92b"

      def install
        bin.install "fling"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/bbkane/fling/releases/download/v0.0.20/fling_0.0.20_linux_armv6.tar.gz"
      sha256 "c5690e10ca5dce3bb7dd69b4d3d54536b2d5c348abfcc783fe2301474f20284e"

      def install
        bin.install "fling"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/fling/releases/download/v0.0.20/fling_0.0.20_linux_amd64.tar.gz"
      sha256 "c4fd2ed2bb21ccea42770d8671c0f6437d83e6c7b8c6ed33ff5e54549358f2e5"

      def install
        bin.install "fling"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bbkane/fling/releases/download/v0.0.20/fling_0.0.20_linux_arm64.tar.gz"
      sha256 "c735724f690033e6b0df5259edb9495a05e2a0c750c341509a7397a925f50c88"

      def install
        bin.install "fling"
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
