# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fling < Formula
  desc "GNU Stow alternative for dotfiles"
  homepage "https://github.com/bbkane/fling"
  version "0.0.19"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bbkane/fling/releases/download/v0.0.19/fling_0.0.19_darwin_arm64.tar.gz"
      sha256 "e42120ed707fc8b301aa1e9d02244d7519d91dad177c10ef955335745463cca5"

      def install
        bin.install "fling"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/fling/releases/download/v0.0.19/fling_0.0.19_darwin_amd64.tar.gz"
      sha256 "2cb878eeb879ddde551539efd0cc04a2ef6cd19a4cff7bed139389972ce2fd4d"

      def install
        bin.install "fling"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bbkane/fling/releases/download/v0.0.19/fling_0.0.19_linux_arm64.tar.gz"
      sha256 "e1d4ea163d8a91b49042582b96b2f89e4b31c4fc4c468c887b0b1c290faf8a00"

      def install
        bin.install "fling"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/bbkane/fling/releases/download/v0.0.19/fling_0.0.19_linux_armv6.tar.gz"
      sha256 "64fa8fd83458f7bc8f376c1c7a5145df7fa667a1c239735982063ed0e9f0b29a"

      def install
        bin.install "fling"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/fling/releases/download/v0.0.19/fling_0.0.19_linux_amd64.tar.gz"
      sha256 "c491815a693fb3317072d35033ed7cc43b686bc9f0d9ee26e8831ea61a4e5c19"

      def install
        bin.install "fling"
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
