# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoRepoJanitor < Formula
  desc "Example Go CLI to model tooling"
  homepage "https://github.com/bbkane/example-go-cli"
  version "0.0.1"

  on_macos do
    url "https://github.com/bbkane/go-repo-janitor/releases/download/v0.0.1/go-repo-janitor_0.0.1_darwin_amd64.tar.gz"
    sha256 "4e4fbcd9d35474bf14665432698b1a35a0adf8fed727aa27c00a17367c17e5b3"

    def install
      bin.install "go-repo-janitor"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the GoRepoJanitor
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/go-repo-janitor/releases/download/v0.0.1/go-repo-janitor_0.0.1_linux_amd64.tar.gz"
      sha256 "88b556ba4450eab0a7fe2fdb574c64919e7d9ce9fa28a9fce03f148b7c3978f1"

      def install
        bin.install "go-repo-janitor"
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
