# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grabbit < Formula
  desc "Grab images from subreddits! Useful for getting interesting wallpapers"
  homepage "https://github.com/bbkane/grabbit"
  version "4.4.20"

  on_macos do
    url "https://github.com/bbkane/grabbit/releases/download/v4.4.20/grabbit_4.4.20_darwin_amd64.tar.gz"
    sha256 "db0985f9e68f4d0ec9e6a26614f75ad268fbd137b7f00fde7620c960613cb3bc"

    def install
      bin.install "grabbit"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Grabbit
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/grabbit/releases/download/v4.4.20/grabbit_4.4.20_linux_amd64.tar.gz"
      sha256 "2d30c0f3c88a4b079bfaafe2a5c2db3f1149230f2c49129d914d776e85d8728f"

      def install
        bin.install "grabbit"
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end

  service do
    run [opt_bin/"grabbit", "grab"]
    run_type :cron
    cron "8 10 * * 1"
  end
end
