# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grabbit < Formula
  desc "Grab images from subreddits! Useful for getting interesting wallpapers"
  homepage "https://github.com/bbkane/grabbit"
  version "4.0.6"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bbkane/grabbit/releases/download/v4.0.6/grabbit_4.0.6_Darwin_x86_64.tar.gz"
    sha256 "be95dea6f19addb5be17781a206e7b4d7aa0e0839737349a06a0c48a859e3245"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bbkane/grabbit/releases/download/v4.0.6/grabbit_4.0.6_Linux_x86_64.tar.gz"
    sha256 "f2080b973b4f7403a057158b7bcb58e0aed6ccf7432f60d7d377d4435fd6d5f1"
  end

  def install
    bin.install "grabbit"
  end

  def caveats; <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>

    <!-- Not sure these are necessary -->
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin</string>
  </dict>

  <key>Label</key>
  <string>#{plist_name}</string>

  <key>ProgramArguments</key>
  <array>
    <string>#{opt_bin}/grabbit</string>
    <string>grab</string>
  </array>

  <key>RunAtLoad</key>
  <true/>

  <key>StartCalendarInterval</key>
  <array>
    <dict>
      <key>Hour</key>
      <integer>10</integer>
      <key>Minute</key>
      <integer>0</integer>
      <!-- Monday is 1 -->
      <key>Weekday</key>
      <integer>1</integer>
    </dict>
  </array>
</dict>

</plist>

  EOS
  end
end
