# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kvcrutch < Formula
  desc "Easily and Safely work with Azure Key Vault"
  homepage "https://github.com/bbkane/kvcrutch"
  version "1.1.9"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bbkane/kvcrutch/releases/download/v1.1.9/kvcrutch_1.1.9_Darwin_x86_64.tar.gz"
    sha256 "508d659191bedcc003b28094dee1a7124a65e5b8e35392c6dda13948a2182d56"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bbkane/kvcrutch/releases/download/v1.1.9/kvcrutch_1.1.9_Linux_x86_64.tar.gz"
    sha256 "c2ad1900e1b029ff3735a135472f03cc605ae0fd38a13389c4a33da11e74e9d4"
  end

  def install
    bin.install "kvcrutch"
  end

  def caveats; <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
  end
end
