# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kvcrutch < Formula
  desc "Easily and Safely work with Azure Key Vault"
  homepage "https://github.com/bbkane/kvcrutch"
  version "1.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bbkane/kvcrutch/releases/download/v1.0.3/kvcrutch_1.0.3_Darwin_x86_64.tar.gz"
    sha256 "6f5ebf2e76174dda7429206587aa09069e938a38df85ff52a09035ba29c0a3d0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bbkane/kvcrutch/releases/download/v1.0.3/kvcrutch_1.0.3_Linux_x86_64.tar.gz"
    sha256 "14db14fa2f33ba5bde4b485db7bb3f204bcf065c76f0c52d3d056d8639d927c9"
  end

  def install
    bin.install "kvcrutch"
  end

  def caveats; <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
  end
end
