# This file was generated by GoReleaser. DO NOT EDIT.
class Kvcrutch < Formula
  desc "Easily and Safely work with Azure Key Vault"
  homepage "https://github.com/bbkane/kvcrutch"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bbkane/kvcrutch/releases/download/v1.0.0/kvcrutch_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "a044db363f5bc0b493b1250cb2385cf92a6f97e7095937b578f187c7036bf46e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bbkane/kvcrutch/releases/download/v1.0.0/kvcrutch_1.0.0_Linux_x86_64.tar.gz"
    sha256 "5aaa4f28848599b065fbd6a95720abe119d99886e2f6259537155afb1d77689f"
  end

  def install
    bin.install "kvcrutch"
  end

  def caveats; <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
  end
end
