# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shovel < Formula
  desc "Example Go CLI to model tooling"
  homepage "https://github.com/bbkane/shovel"
  version "0.0.5"

  on_macos do
    url "https://github.com/bbkane/shovel/releases/download/v0.0.5/shovel_0.0.5_darwin_amd64.tar.gz"
    sha256 "e568ddb62a180ed87a2471d90ffc7d860a26941c58408e2ad162c5c2703503f7"

    def install
      bin.install "shovel"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Shovel
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/shovel/releases/download/v0.0.5/shovel_0.0.5_linux_amd64.tar.gz"
      sha256 "4c7cd8108f2fac9ea4bfa9939f9c8a866f6b840bf8b2d1b0cfe411223a0d9341"

      def install
        bin.install "shovel"
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
