# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shovel < Formula
  desc "Example Go CLI to model tooling"
  homepage "https://github.com/bbkane/shovel"
  version "0.0.3"

  on_macos do
    url "https://github.com/bbkane/shovel/releases/download/v0.0.3/shovel_0.0.3_darwin_amd64.tar.gz"
    sha256 "ce9a552f3f2f9066ed3fc0e7967b4c3baff4d5ac1367828b996bc4cc059e0c19"

    def install
      bin.install "shovel"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Shovel
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/shovel/releases/download/v0.0.3/shovel_0.0.3_linux_amd64.tar.gz"
      sha256 "817766b763e514a3a78b9f6953c8f911d47476b571c3db9ab016cdbcf1733412"

      def install
        bin.install "shovel"
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
