# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shovel < Formula
  desc "Example Go CLI to model tooling"
  homepage "https://github.com/bbkane/shovel"
  version "0.0.14"

  on_macos do
    url "https://github.com/bbkane/shovel/releases/download/v0.0.14/shovel_0.0.14_darwin_amd64.tar.gz"
    sha256 "272c881b58ef26157a253355d272cc7f8b27ec8ec561bb7ab4b252bd4620dd73"

    def install
      bin.install "shovel"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Shovel
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/shovel/releases/download/v0.0.14/shovel_0.0.14_linux_amd64.tar.gz"
      sha256 "4b20d4169f4a3738701792971fa8173696de377744df1f1a18df01a1c24bba98"

      def install
        bin.install "shovel"
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
