# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Starghaze < Formula
  desc "Save GitHub Starred Repo Information"
  homepage "https://github.com/bbkane/starghaze"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/starghaze/releases/download/v0.0.3/starghaze_0.0.3_darwin_amd64.tar.gz"
      sha256 "bb8b144507d8a8d3f445072bfbd95349694cf2287b1e4312350bd7f01fabc897"

      def install
        bin.install "starghaze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/starghaze/releases/download/v0.0.3/starghaze_0.0.3_linux_amd64.tar.gz"
      sha256 "8b625ac939dbcae6320cdcdb1ee2cfb161f7575bb75f863c57c4cb7f316f2a50"

      def install
        bin.install "starghaze"
      end
    end
  end

  def caveats; <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
  end
end
