# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Starghaze < Formula
  desc "Save GitHub Starred Repo Information"
  homepage "https://github.com/bbkane/starghaze"
  version "0.0.12"

  on_macos do
    url "https://github.com/bbkane/starghaze/releases/download/v0.0.12/starghaze_0.0.12_darwin_amd64.tar.gz"
    sha256 "d8c2ef098fb47a56a14154e60387a7893f8de6b5ad60d1e85a94ddfec95a099a"

    def install
      bin.install "starghaze"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Starghaze
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/starghaze/releases/download/v0.0.12/starghaze_0.0.12_linux_amd64.tar.gz"
      sha256 "18562593544d7d4e981721eb72b3bd11c2629c98bb32932765cc425f4f614f2a"

      def install
        bin.install "starghaze"
      end
    end
  end

  def caveats; <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
  end
end
