# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Starghaze < Formula
  desc "Save GitHub Starred Repo Information"
  homepage "https://github.com/bbkane/starghaze"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/starghaze/releases/download/v0.0.8/starghaze_0.0.8_darwin_amd64.tar.gz"
      sha256 "7f2c949a273c8764b08798e69f439b45b9912e5ff1e305e959038fd880582370"

      def install
        bin.install "starghaze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/starghaze/releases/download/v0.0.8/starghaze_0.0.8_linux_amd64.tar.gz"
      sha256 "4f90008504cb17c7d74a51a167e89f8c68452d5379a5a7e1d3793b3bdd300d23"

      def install
        bin.install "starghaze"
      end
    end
  end

  def caveats; <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
  end
end
