# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tablegraph < Formula
  desc "Create graphs from CSVs"
  homepage "https://github.com/bbkane/tablegraph"
  version "0.0.4"

  on_macos do
    url "https://github.com/bbkane/tablegraph/releases/download/v0.0.4/tablegraph_0.0.4_darwin_amd64.tar.gz"
    sha256 "e195c8d95944f15e29976c7cff366219a5c67794e5bf8543e892b046d89f719e"

    def install
      bin.install "tablegraph"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Tablegraph
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/tablegraph/releases/download/v0.0.4/tablegraph_0.0.4_linux_amd64.tar.gz"
      sha256 "8472939423b328a8ef39ef9490128d8b7bacb7bad244c5c81576cb10a27d2302"

      def install
        bin.install "tablegraph"
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
