# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tablegraph < Formula
  desc "Grab images from subreddits! Useful for getting interesting wallpapers"
  homepage "https://github.com/bbkane/grabbit"
  version "0.0.2"

  on_macos do
    url "https://github.com/bbkane/tablegraph/releases/download/v0.0.2/tablegraph_0.0.2_darwin_amd64.tar.gz"
    sha256 "a48ebea226af1719c751e5bf3824bf6dbd5e4cc7c3797e3bb0d2465ba452ace5"

    def install
      bin.install "tablegraph"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Tablegraph
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/tablegraph/releases/download/v0.0.2/tablegraph_0.0.2_linux_amd64.tar.gz"
      sha256 "dbf5d67157b36d0e4cfe44943f57669ac4a1326f596af3f1d4fb7a700c47544a"

      def install
        bin.install "tablegraph"
      end
    end
  end

  def caveats; <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>

    <!-- Not sure these are necessary -->
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin</string>
  </dict>

  <key>Label</key>
  <string>#{plist_name}</string>

  <key>ProgramArguments</key>
  <array>
    <string>#{opt_bin}/grabbit</string>
    <string>grab</string>
  </array>

  <key>RunAtLoad</key>
  <true/>

  <key>StartCalendarInterval</key>
  <array>
    <dict>
      <key>Hour</key>
      <integer>10</integer>
      <key>Minute</key>
      <integer>0</integer>
      <!-- Monday is 1 -->
      <key>Weekday</key>
      <integer>1</integer>
    </dict>
  </array>
</dict>

</plist>

  EOS
  end
end
