# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tablegraph < Formula
  desc "Create graphs from CSVs"
  homepage "https://github.com/bbkane/tablegraph"
  version "0.0.3"

  on_macos do
    url "https://github.com/bbkane/tablegraph/releases/download/v0.0.3/tablegraph_0.0.3_darwin_amd64.tar.gz"
    sha256 "337f237c62e8298422a3ffa05ce1be95204fa853f5bba5f73f1d407b0a6fbd5f"

    def install
      bin.install "tablegraph"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Tablegraph
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bbkane/tablegraph/releases/download/v0.0.3/tablegraph_0.0.3_linux_amd64.tar.gz"
      sha256 "903ac3cd256d32e9135837a2bf7f8c5a09b5571ff8731b9a6767febb8837213e"

      def install
        bin.install "tablegraph"
      end
    end
  end

  def caveats; <<~EOS
    Unfortunately, Apple wants to charge developers $100/year to distribute
    their apps without a big scary "... the developer cannot be verified"
    warning. I'm not willing to pay that to give away free apps.
    See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
  EOS
  end
end
