# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toddlerevents < Formula
  desc "Write Bay Area toddler library events to a README.md"
  homepage "https://github.com/bbkane/toddlerevents"
  version "0.0.3"

  on_macos do
    url "https://github.com/bbkane/toddlerevents/releases/download/v0.0.3/toddlerevents_0.0.3_darwin_amd64.tar.gz"
    sha256 "2c41849203a2ebf61c1c5a991a78e0562bcee940328f8545efef4ea2b4ba730a"

    def install
      bin.install "toddlerevents"
      generate_completions_from_executable(bin/"toddlerevents", "completion", shells: [:zsh])
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Toddlerevents
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/bbkane/toddlerevents/releases/download/v0.0.3/toddlerevents_0.0.3_linux_amd64.tar.gz"
      sha256 "f9dbd411477e2a88da1a2bbedc87eec4a03b4b7abe4eb2a7586dad63eee72aaf"
      def install
        bin.install "toddlerevents"
        generate_completions_from_executable(bin/"toddlerevents", "completion", shells: [:zsh])
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
