# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toddlerevents < Formula
  desc "Write Bay Area toddler library events to a README.md"
  homepage "https://github.com/bbkane/toddlerevents"
  version "0.0.2"

  on_macos do
    url "https://github.com/bbkane/toddlerevents/releases/download/v0.0.2/toddlerevents_0.0.2_darwin_amd64.tar.gz"
    sha256 "ab51971165fccdf108b3885f48665a01487f49711039d7c607bad33972481daa"

    def install
      bin.install "toddlerevents"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Toddlerevents
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bbkane/toddlerevents/releases/download/v0.0.2/toddlerevents_0.0.2_linux_amd64.tar.gz"
        sha256 "a5da82354cf89f1fd2e7fdefb058e308a427f47ead6043bd659425446141aab4"

        def install
          bin.install "toddlerevents"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
