# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toddlerevents < Formula
  desc "Write Bay Area toddler library events to a README.md"
  homepage "https://github.com/bbkane/toddlerevents"
  version "0.0.4"

  on_macos do
    url "https://github.com/bbkane/toddlerevents/releases/download/v0.0.4/toddlerevents_0.0.4_darwin_amd64.tar.gz"
    sha256 "851c4ecd12e775a4282ac1c13ab495ea9b962462869e4da26c2366467c4f4304"

    define_method(:install) do
      bin.install "toddlerevents"
      generate_completions_from_executable(bin/"toddlerevents", "completion", shells: [:bash, :fish, :zsh])
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Toddlerevents
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bbkane/toddlerevents/releases/download/v0.0.4/toddlerevents_0.0.4_linux_amd64.tar.gz"
      sha256 "25e18ee34c12f2eb9d3b86df1b18a2cdaf7eedd4888fa39be2df754e083ba50b"
      define_method(:install) do
        bin.install "toddlerevents"
        generate_completions_from_executable(bin/"toddlerevents", "completion", shells: [:bash, :fish, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      Unfortunately, Apple wants to charge developers $100/year to distribute
      their apps without a big scary "... the developer cannot be verified"
      warning. I'm not willing to pay that to give away free apps.
      See https://www.macworld.com/article/3140183/how-to-install-an-app-in-macos-sierra-thats-not-signed-by-a-developer.html to work around that
    EOS
  end
end
